### ISSUE TITLE
Mobile - video distortion on level-2 pages

### ISSUE THREAD

**Issue by aaubryiwu** [iwu/iwu-website#102]
Both Chrome & Safari:

![3bad7d78-2c85-11e6-93c5-c02e44e35388](https://cloud.githubusercontent.com/assets/14187046/15863938/9861ee68-2c9a-11e6-8a0b-00062c897178.PNG)

**Comment by michaelcgorman** [comment]
Alright, check it out. I'm seeing some that aren't wide enough anymore, but I think it's better on test than prod now, so I can push it live as an interim solution if you guys think it's okay.

**Comment by robertfrankiii** [comment]
Looks better to me.

**Comment by aaubryiwu** [comment]
Agreed. This is probably the worst offender so far now, but still better than the distortion.

![img_1032](https://cloud.githubusercontent.com/assets/14187046/15866341/ca650ffe-2ca3-11e6-89f3-5eadc5a55ed9.PNG)

**Comment by robertfrankiii** [comment]
Just noticed that they aren't looking that great at desktop anymore:

![screen shot 2016-06-07 at 2 19 27 pm](https://cloud.githubusercontent.com/assets/14199085/15871568/01311322-2cbb-11e6-831f-52f07067ee96.png)

**Comment by michaelcgorman** [comment]
Still better than it was. Figuring out the whitespace. And sometimes some nearby stuff being pushed off-screen.

**Comment by michaelcgorman** [comment]
Alright, I was just chatting with Curtis about the problems with the way this is being done. I think I have a solution. Instead of playing the video inside the space where the placeholder image is displayed, we pop up a modal dialog for the video. That shouldn't be too difficult to build. I'll work along that vein.

**Comment by michaelcgorman** [comment]
All of the second-level videos are fixed.

**Comment by aaubryiwu** [comment]
Didn't check mobile till today (portal day, sorry.)

Seem to be problems with videos & now with nav & links, perhaps triggered by this? -- 
Tried both Chrome & Safari, iPhone6s:

- For all but "After IWU," the Nav & all links on the page won't work.

- About - video plays, but Nav & links on page won't work for me; for @robertfrankiii, all links launch the video

- Academics - Video display sizes OK but won't play

- Admissions & Student Life - Videos display in thin strip; won't play

**Comment by michaelcgorman** [comment]
Alright, I think I've fixed all of this _other than_ the thin-strip display issue in test. Check it out and let me know if I should deploy this almost-fix. I think it's 90% of the way to a complete solution, but not quite perfect yet.

**Comment by michaelcgorman** [comment]
Also, I'd like to see if I can make videos autoplay rather than showing up in the modal when someone clicks the trigger image. On mobile, where videos play fullscreen, that would entirely eliminate the need for the modal. On desktop, it would still show up in the modal, but you just wouldn't have to click a second time to get it to play.

**Comment by aaubryiwu** [comment]
Agree on deploying. Looks like they at least play -- and the nav & other links work now. THANKS!!! 
And I think you're right on autoplay after the initial click.

**Comment by michaelcgorman** [comment]
Alright. Deployed.

**Comment by michaelcgorman** [comment]
Alright, the initial problem is fixed, so I'm opening new issues for the remaining tasks:

- #109 - Some second-level videos display with little height
- #110 - Autoplay videos on second-level pages
- #111 - Eliminate video modal on mobile (second-level pages)
