### ISSUE TITLE
Level 2 pages: Header Carousel area cut off

### ISSUE THREAD

**Issue by robertfrankiii** [iwu/iwu-website#112]
I'm still seeing this bug on my phone when I load the page in Safari and Chrome.

![img_0700](https://cloud.githubusercontent.com/assets/14199085/16209469/c80a2088-36fc-11e6-863b-1036996f7366.PNG)

**Comment by michaelcgorman** [comment]
Alright, give it another shot.

**Comment by robertfrankiii** [comment]
That worked, but as I scroll down the image area gets a little taller and shrinks again when I scroll back up.

**Comment by michaelcgorman** [comment]
Double-check your cache; I just made another change. Also, can you confirm that it's related to scrolling and not carousel content changes?

**Comment by robertfrankiii** [comment]
Cleared cache and now it works fine in Safari. Mobile Chrome still has the scrolling bug that happens on all of the level two pages (even the ones without multiple images in the carousel)

**Comment by michaelcgorman** [comment]
My nose is running today, so I don't want to handle your phone. Is this easily screenshottable?

**Comment by michaelcgorman** [comment]
Oh, wait - actually, I think I can see what you're talking about on my own phone. Weird. I can try to fix, but would you say that its current state is better than what's out there on production? I'm thinking about deploying this temporarily just to improve the situation before I start playing around more.

**Comment by robertfrankiii** [comment]
Yes, I would say it's better than what's on production now.

Yeah, it's more of a behavior so it's difficult to screenshot.

**Comment by michaelcgorman** [comment]
Alright, deployed. I'll keep mulling what could be happening. Chrome's desktop emulator doesn't do the same thing, so it's harder to diagnose. But at least it's not terrible anymore.

**Comment by michaelcgorman** [comment]
Ah, figured out what it is. The new height is defined as 80% of viewport height, but the viewport changes height on scroll because of the address bar hiding/showing itself.

**Comment by michaelcgorman** [comment]
Relevant: https://bugs.chromium.org/p/chromium/issues/detail?id=428132

**Comment by michaelcgorman** [comment]
It looks like the Chrome team is actively working on a fix. The talk right now appears to be heading in the direction of trying to match Safari's functionality - where the vh units are defined by the height of the viewport with the URL bar collapsed even if it's not, so it doesn't change when the URL bar hides/shows itself.

Since it's not impacting anything critical (it's just a kinda glitchy-feeling UX) I'm gonna chalk this up to a browser bug that will be fixed soon and close the issue.
