### ISSUE TITLE
Anchor Links

### ISSUE THREAD

**Issue by robertfrankiii** [iwu/iwu-website#113]
Looks like anchor links are zooming too far down the page. I'm assuming the fixed header is the problem again? Can we get it to zoom to a little farther above the anchor so that the header and seal don't obscure it?

**Comment by michaelcgorman** [comment]
Example?

**Comment by robertfrankiii** [comment]
Any of the ART links on this page: https://www.iwu.edu/art/courses/suggested-curriculum.html
