### ISSUE TITLE
Portal - User lookup

### ISSUE THREAD

**Issue by michaelcgorman** [iwu/iwu-website#13]
New portal should have a channel for admins to look up info about users. Curtis' request:

> Lookup should be able to search for students, staff, faculty, and alumni. Should report a user’s first, last, and preferred name. Other details include role, birthdate, major, ID#, last 4 of SSN.

Most of this data can come from AD. Birthdate and SSN shard are not in that repository and will be logistically more complicated. Perhaps launch without?

**Comment by aaubryiwu** [comment]
Do we really need last 4 of SSN? Eek!

**Comment by michaelcgorman** [comment]
@ckelch - MZehr says we should use the AD search user credentials he gave you for Luminis. Could you get those to me offline?

**Comment by michaelcgorman** [comment]
This issue was moved to iwu/my.iwu.edu#6
