### ISSUE TITLE
Add Qualtrics to Special Account Request page

### ISSUE THREAD

**Issue by katebrowne09** [iwu/iwu-website#14]
Add "a Qualtrics account" to list of options on the Special Account Request page with me as the approver.

**Comment by michaelcgorman** [comment]
@katebrowne09 Are there any other fields you want to know other than their NetID? Any additional questions the form should ask?

**Comment by katebrowne09** [comment]
No, just the NetID will work. I only need a name and email address to
create the account.

On Wed, Sep 9, 2015 at 1:51 PM, Michael C Gorman <notifications@github.com>
wrote:

> @katebrowne09 <https://github.com/katebrowne09> Are there any other
> fields you want to know other than their NetID? Any additional questions
> the form should ask?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iwu/iwu-website/issues/14#issuecomment-139005129>.
>



-- 
*Kate Browne*
ITS--Technology Trainer
(309) 556-3890
kbrowne@iwu.edu

**Comment by michaelcgorman** [comment]
Done.
