### ISSUE TITLE
Image carousel font sizes

### ISSUE THREAD

**Issue by michaelcgorman** [iwu/iwu-website#18]
Rick mentioned that the font size on image carousels (header / subhead) does not scale at all by screen size. Maybe that should change? @robertfrankiii - any suggestions?

**Comment by michaelcgorman** [comment]
Think this is still an issue in the redesign, @robertfrankiii?

**Comment by robertfrankiii** [comment]
Sorry for the delay with this. It's sort of difficult to tell because the carousel snippet seems to be broken on test. Green links should be white and next/previous text don't need to be there. I think if we take the font size down to 14, that should work - I'll have to see it to know, though.

**Comment by michaelcgorman** [comment]
Just got around to this. How's this?
![screen shot 2015-12-09 at 13 27 05](https://cloud.githubusercontent.com/assets/313667/11696164/94d0e14c-9e78-11e5-90c2-ceea52bed54e.png)

**Comment by robertfrankiii** [comment]
Oops, I forgot to say "at the 480px breakpoint and below." It definitely shouldn't be smaller than the body font size at 768 and up. Sorry about that confusion.

**Comment by michaelcgorman** [comment]
Alright, check it out again.

**Comment by robertfrankiii** [comment]
Much better, thanks!
