### ISSUE TITLE
Portal - Home Page

### ISSUE THREAD

**Issue by ckelch** [iwu/iwu-website#32]
Here is the new portal home page I mocked up. Since we will be presenting a demo either at the next All ITS meeting or at the next DRIP, try and integrate this in with your portal pages.

https://www.iwu.edu/1world/myiwu.html

**Comment by michaelcgorman** [comment]
How do you envision this being "integrated" with the other piece of the
portal?

On 12 November 2015 at 09:05, ckelch <notifications@github.com> wrote:

> Here is the new portal home page I mocked up. Since we will be presenting
> a demo either at the next All ITS meeting or at the next DRIP, try and
> integrate this in with your portal pages.
>
> https://www.iwu.edu/1world/myiwu.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iwu/iwu-website/issues/32>.
>



-- 
Michael Gorman '10
Señor Web Developer
Bicycle Committee Chair
Illinois Wesleyan University
309-556-3262
mgorman@iwu.edu
@michaelcgorman <https://twitter.com/michaelcgorman>

**Comment by ckelch** [comment]
Kind of like it is right now. When they click on the button for secure access information they are taken to the CAS auth page or if already logged in they move to the php portal page. Is that what you meant?

**Comment by michaelcgorman** [comment]
So, don't make any changes?

On 12 November 2015 at 09:39, ckelch <notifications@github.com> wrote:

> Kind of like it is right now. When they click on the button for secure
> access information they are taken to the CAS auth page or if already logged
> in they move to the php portal page. Is that what you meant?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iwu/iwu-website/issues/32#issuecomment-156141704>.
>



-- 
Michael Gorman '10
Señor Web Developer
Bicycle Committee Chair
Illinois Wesleyan University
309-556-3262
mgorman@iwu.edu
@michaelcgorman <https://twitter.com/michaelcgorman>

**Comment by ckelch** [comment]
Yeah, this was just for your information. I don't think I had given you the un-authenticated home page link yet. You already removed the redundant calendar. Closed!
