### ISSUE TITLE
Portal - Announcement Roles

### ISSUE THREAD

**Issue by ckelch** [iwu/iwu-website#33]
Need announcements designated to show in the portal to only show to selected roles. Current roles in MyIWU are as follows:

Faculty-FT
Faculty-PT
Staff-Exempt
Staff-Non-Exempt
Student-Male
Student-Female
Student-Freshmen
Student-Sophomore
Student-Junior
Student-Senior
Student-May-Term
Retirees

Email announcements will go to Regroup.

**Comment by michaelcgorman** [comment]
Announcement creation form has been updated. Data source not yet integrated.

On 12 November 2015 at 09:16, ckelch <notifications@github.com> wrote:

> Need announcements designated to show in the portal to only show to
> selected roles. Current roles in MyIWU are as follows:
>
> Faculty-FT
> Faculty-PT
> Staff-Exempt
> Staff-Non-Exempt
> Student-Male
> Student-Female
> Student-Freshmen
> Student-Sophomore
> Student-Junior
> Student-Senior
> Student-May-Term
> Retirees
>
> Email announcements will go to Regroup.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iwu/iwu-website/issues/33>.
>



-- 
Michael Gorman '10
Señor Web Developer
Bicycle Committee Chair
Illinois Wesleyan University
309-556-3262
mgorman@iwu.edu
@michaelcgorman <https://twitter.com/michaelcgorman>

**Comment by michaelcgorman** [comment]
This issue was moved to iwu/my.iwu.edu#5
