### ISSUE TITLE
Portal - Announcement Admin Interface

### ISSUE THREAD

**Issue by ckelch** [iwu/iwu-website#34]
Need an announcement interface to use same fields as the announcement request form. Will use role to show announcement to appropriate audience. Should show latest 10 announcements with link to show more (if there are more than 10). Announcement should show Subject of each announcement as a link. This link will take them to details of announcement. Default announcement will show for 7 days if no expiration is set.

**Comment by michaelcgorman** [comment]
Is there a reason each announcement has to be a link to a page with more
info? I feel like users would probably prefer not to have to click to learn
more about a specific announcement. Announcements are required to be brief
enough (150 words) that displaying current announcements all in one view
wouldn't take up too much space.

On 12 November 2015 at 09:22, ckelch <notifications@github.com> wrote:

> Need an announcement interface to use same fields as the announcement
> request form. Will use role to show announcement to appropriate audience.
> Should show latest 10 announcements with link to show more (if there are
> more than 10). Announcement should show Subject of each announcement as a
> link. This link will take them to details of announcement. Default
> announcement will show for 7 days if no expiration is set.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iwu/iwu-website/issues/34>.
>



-- 
Michael Gorman '10
Señor Web Developer
Bicycle Committee Chair
Illinois Wesleyan University
309-556-3262
mgorman@iwu.edu
@michaelcgorman <https://twitter.com/michaelcgorman>

**Comment by ckelch** [comment]
Maybe we could do this if we cut down on the announcements shown from 10 to maybe 6?? Seems like this would get very text-bomb looking.

**Comment by michaelcgorman** [comment]
Done.

**Comment by michaelcgorman** [comment]
This issue was moved to iwu/my.iwu.edu#4
