### ISSUE TITLE
Portal - 3-Column Interface

### ISSUE THREAD

**Issue by ckelch** [iwu/iwu-website#35]
Everyone has complained that the current interface is too narrow. Would like a 3 column interface to show all content in a more desirable fashion.

**Comment by ckelch** [comment]
Would be nice if one column could be wider than the other two. Since we will be in control of content, not every content item will be added to the portal with a "wide" designation.

**Comment by michaelcgorman** [comment]
This issue was moved to iwu/my.iwu.edu#3
