### ISSUE TITLE
Portal - Admin Interface for New Content

### ISSUE THREAD

**Issue by ckelch** [iwu/iwu-website#37]
Users designated as portal content managers should have an interface for creating, removing and repositioning content within the portal. It might be nice to show past content in the admin interface in case content is used on an annual basis depending on the time of year. Users should only see the content they have created in the past.

**Comment by michaelcgorman** [comment]
Gotta be more specific about content management. Each channel has its own content management properties. Discussion of content management for specific channels should be handled in individual issues for each channel.

Repositioning of channels is handled automatically on pageload and when channels change size (e.g. the user collapses or opens a channel or goes to a new screen within a channel), so I'm not sure what you mean by repositioning.
