### ISSUE TITLE
Test Hompage: Carousel Arrows

### ISSUE THREAD

**Issue by robertfrankiii** [iwu/iwu-website#42]
On phone sized screens the content in the main carousel on the homepage overlaps with the side arrows. Although both still function fine, it looks odd. Could the arrows move up with the content (we will obviously have to be careful with word counts)?

**Comment by michaelcgorman** [comment]
Positioning the controls relative to the text would require a structural overhaul. How about top: 40% rather than top: 50%? CSS has been updated to reflect this option.

**Comment by robertfrankiii** [comment]
I think that gives us more room to play with. We will still need to watch our word counts more closely.
