### ISSUE TITLE
Test Department: Banner Image Area

### ISSUE THREAD

**Issue by robertfrankiii** [iwu/iwu-website#44]
Change head banner image area size back to current site size. Would it be possible to scale the height smaller as the screen's width decreases? Trying to solve the problem of the header image area taking too much space on phones.

**Comment by michaelcgorman** [comment]
I've set #header-wrap's height to 25% of the viewport width. How does that look?

**Comment by robertfrankiii** [comment]
Personally, I think the height is too large at 1200px width and too small at <48px.

**Comment by michaelcgorman** [comment]
Alright. Suggestions? Options include:
- setting max and min height
- different fixed heights at different breakpoints
- different viewport-scaled heights at different breakpoints

BTW, I assume you mean it's too small at <480px, right? 'Cause I, for one, am not testing this thing at 47px wide.

**Comment by robertfrankiii** [comment]
I definitely meant <480px, sorry! I think setting a max and min height should do it, because as long as it isn't larger than the current site is at 1200px screens and is larger at mobile screens than it currently is on test, everything in between should look fine. My suggested min-height would be 150px.

**Comment by michaelcgorman** [comment]
Done.
