### ISSUE TITLE
Test Snippet: Tabs

### ISSUE THREAD

**Issue by robertfrankiii** [iwu/iwu-website#51]
Tab snippet doesn't work (visually) on department pages. Would it be possible to use what we have currently on the live site but without the left and right borders and Wesleyan green instead of the lighter green? So basically keep the top line with the tabs and add a horizontal rule after the tab content. I feel like this will work better for homepage and departments.

**Comment by michaelcgorman** [comment]
Check it out now.

**Comment by robertfrankiii** [comment]
Looks much better, but I forgot to mention the color change for the border lines: #e2e0d6

**Comment by michaelcgorman** [comment]
Done.
