### ISSUE TITLE
Test Department: Faculty Contact info

### ISSUE THREAD

**Issue by robertfrankiii** [iwu/iwu-website#53]
The faculty contact information callout box isn't displaying correctly on their bio pages
<img width="883" alt="screen shot 2015-11-13 at 1 45 50 pm" src="https://cloud.githubusercontent.com/assets/14199085/11155718/e442009c-8a0c-11e5-820e-1997f686150a.png">

**Comment by michaelcgorman** [comment]
How's it look now?

**Comment by robertfrankiii** [comment]
Awesome!
