### ISSUE TITLE
Test Snippet: Callout Box

### ISSUE THREAD

**Issue by robertfrankiii** [iwu/iwu-website#55]
The callout box "color boxes" don't scale correctly on phones. They should always span the entire width of the callout box. This might be because it's the mobile version of Chrome (?)
![img_0512](https://cloud.githubusercontent.com/assets/14199085/11155841/c69e93f6-8a0d-11e5-81ad-8aa3ba9cf7e4.jpg)

**Comment by michaelcgorman** [comment]
I am unable to replicate this issue.

**Comment by robertfrankiii** [comment]
I'm still seeing the same thing, but only on my phone. Would you like me to bring it over so you can use your developer tools on it?

**Comment by michaelcgorman** [comment]
I am now able to replicate this issue on my phone, but not in Chrome's desktop-based iPhone emulator. Weird.

**Comment by michaelcgorman** [comment]
Fixed.
