### ISSUE TITLE
Test Snippets: Carousel and Video

### ISSUE THREAD

**Issue by robertfrankiii** [iwu/iwu-website#56]
These two snippets don't seem to be floating to either side anymore on test.

**Comment by michaelcgorman** [comment]
Weird. I'd modified the .left and .right styles to .left:not(a.item) and .right:not(a.item), which I wouldn't expect to affect these, which are <div class="right"> with a.items inside, but it did. I've changed those selectors back and made a rule for a.left.item and a.right.item that reset float and margin instead. That might have unintended consequences elsewhere, but they should be easier to deal with.
