### ISSUE TITLE
Snippet Request: Video Grid

### ISSUE THREAD

**Issue by robertfrankiii** [iwu/iwu-website#58]
We would like to create compact grids of videos and the video snippet right now can't really give us that. The best we can do is put videos in a 2col flex grid - but the videos overlap at certain sizes. If a video grid is something you can do, which would be easier: creating a new video grid snippet, or modifying the current video snippet to size down in the 2col and 3col flex grids?
Thoughts?

**Comment by michaelcgorman** [comment]
Could you link me to an example of a broken page, with a screenshot of how it currently looks?

It'll almost certainly be easier to fix what we have than build (and maintain) something entirely different.

**Comment by robertfrankiii** [comment]
https://www.iwu.edu/majors/archive/frank-test.html
Here is a screen shot at full screen and you can tell the left video is out of the content area:
<img width="1035" alt="screen shot 2015-12-04 at 10 29 46 am" src="https://cloud.githubusercontent.com/assets/14199085/11595008/d592044a-9a72-11e5-8a57-29d031772964.png">
And here is a screenshot when sized down. You can tell based on the other screenshot how much is cut off by the video on the right and the left side of the screen
<img width="780" alt="screen shot 2015-12-04 at 10 34 16 am" src="https://cloud.githubusercontent.com/assets/14199085/11595052/158ffb6a-9a73-11e5-9846-72c32ec39973.png">

**Comment by michaelcgorman** [comment]
This is only happening for me when I resize the page. The video snippet determines its size using Javascript on pageload; if you reload the page after resizing, it should look fine.

I could look into running the resizing code when the window width changes, but IMO it's pretty rare that a regular user would resize their browser window while on one of these pages.

Thoughts?

**Comment by robertfrankiii** [comment]
Wow, I'm an idiot. I could have sworn that at one point in time, putting 3 videos in a 3col flex grid didn't resize them so they just overlapped...  I think you just solved my problem because it clearly works:
https://www.iwu.edu/1world/music/index-1.html

I agree that it's probably rare so I don't see any reason to change this. Thanks!
