### ISSUE TITLE
Page Properties - Update News Categories

### ISSUE THREAD

**Issue by aaubryiwu** [iwu/iwu-website#59]
Not urgent, but if at some point it's feasible to update these, here's my attempt at a refined list:

[categories.txt](https://github.com/iwu/iwu-website/files/59616/categories.txt)

**Comment by michaelcgorman** [comment]
Here's the difference, as far as I can tell, between your request and what currently exists:

![screen shot 2015-12-21 at 10 09 04](https://cloud.githubusercontent.com/assets/313667/11934996/f2444944-a7ca-11e5-8326-4d662022b4d7.png)

Look good?

**Comment by michaelcgorman** [comment]
(New on left, old on right.)

**Comment by aaubryiwu** [comment]
Looks good! Thanks!!

**Comment by michaelcgorman** [comment]
One page (/giving/how/annfund_10things.pcf) uses "gem".

33 pages use "liberal arts":
* /giving/how/annfund_10things.pcf
* /jwprc/gallery.pcf
* /lrc/language-school-for-kids/spanish_french_saturday_school.pcf
* /lrc/language-school-for-kids/registration.pcf
* /lrc/language-school-for-kids/LRC_after_school_program.pcf
* /lrc/language-school-for-kids/about.pcf
* /melloncenter/strategic-curricular-planning.pcf
* /melloncenter/exemplarygrantproposals.pcf
* /melloncenter/faculty-development.pcf
* /melloncenter/index.pcf
* /melloncenter/FDC.pcf
* /melloncenter/rubrics-and-syllabi.pcf
* /melloncenter/gened-gateway.pcf
* /melloncenter/external-review/political-science-review/index.pcf
* /melloncenter/curriculum.pcf
* /melloncenter/exemplary-proposals.pcf
* /melloncenter/contact.pcf
* /melloncenter/events.pcf
* /melloncenter/teaching-learning/course-clustering-1.pcf
* /melloncenter/teaching-learning/course-clustering.pcf
* /melloncenter/teaching-learning/teaching-technology.pcf
* /melloncenter/teaching-learning/collaboration.pcf
* /melloncenter/teaching-learning/teaching-commons.pcf
* /melloncenter/teaching-learning/team-teaching.pcf
* /melloncenter/teaching-circles.pcf
* /melloncenter/curricular-initiatives/index.pcf
* /melloncenter/CC.pcf
* /melloncenter/mayterm/student-resources.pcf
* /melloncenter/mayterm/index.pcf
* /melloncenter/mayterm/faculty-resources.pcf
* /melloncenter/mayterm/index-new.pcf
* /melloncenter/mayterm/photo-contest.pcf
* /melloncenter/mayterm/reports/index.pcf

I can remove the option for any pages not already using these two filters to use them in the future, or I can remove it from all pages, including the ones currently using them. Which would you prefer?

**Comment by aaubryiwu** [comment]
Spot checking, it looks like they're selecting multiple categories for those pages, so the unused feeds shouldn't be noticed if they're removed altogether. So I'd opt for the latter, assuming that's the cleaner choice.

**Comment by michaelcgorman** [comment]
I've run the following find-and-replaces so far:
* `<option value="gem" selected="(true|false)">Gems of IWU</option>([\n\r\s]*)<option value="liberal-arts" selected="(true|false)">Value of the Liberal Arts</option>` → [empty string]
* `<option value="students" selected="(true|false)">Students</option>([\n\r\s]*)<option value="art" selected="(true|false)">Art</option>` → `<option value="students" selected="$1">Students</option>$2<option value="accounting" selected="false">Accounting and Finance</option>$2<option value="art" selected="$3">Art</option>`
* `<option value="languages" selected="(true|false)">Languages</option>([\n\r\s]*)<option value="math" selected="(true|false)">Math</option>` → `<option value="languages" selected="$1">Languages</option>$2<option value="german" selected="false">German</option>$2<option value="hispanic-studies" selected="false">Hispanic Studies</option>$2<option value="math" selected="$3">Math</option>`

Interfaith, Research, Study Abroad, Internships, and Graduate Success still to come.

The global find-and-replace process is excruciatingly slow...

**Comment by michaelcgorman** [comment]
I've added Interfaith:
`<option value="athletics" selected="(true|false)">Athletics</option>([\n\r\s]*)<option value="philanthropy" selected="(true|false)">Philanthropy</option>` → `<option value="athletics" selected="$1">Athletics</option>$2<option value="chapel" selected="false">Interfaith</option>$2<option value="philanthropy" selected="$3">Philanthropy</option>`

**Comment by michaelcgorman** [comment]
Research is done:
`<option value="philanthropy" selected="(true|false)">Philanthropy</option>([\n\r\s]*)<option value="prospective-students" selected="(true|false)">Prospective Students</option>` → `<option value="philanthropy" selected="$1">Philanthropy</option>$2<option value="research" selected="false">Research</option>$2<option value="prospective-students" selected="$3">Prospective Students</option>`

**Comment by michaelcgorman** [comment]
Philanthropy is done:
`<option value="philanthropy" selected="(true|false)">Philanthropy</option>([\n\r\s]*)<option value="prospective-students" selected="(true|false)">Prospective Students</option>` → `<option value="philanthropy" selected="$1">Philanthropy</option>$2<option value="research" selected="false">Research</option>$2<option value="prospective-students" selected="$3">Prospective Students</option>`

**Comment by michaelcgorman** [comment]
And Internships and Graduate Success are added:
`([\n\r\s]*)<option value="speakers" selected="(true|false)">Speakers</option>` → `$1<option value="speakers" selected="$2">Speakers</option>$1<option value="internships" selected="false">Internships</option>$1<option value="grads" selected="false">Graduate success</option>`

Done.

**Comment by aaubryiwu** [comment]
<3
