### ISSUE TITLE
Page Properties - Update Social 

### ISSUE THREAD

**Issue by aaubryiwu** [iwu/iwu-website#60]
Are there hopes of applying page properties across directories? 

In the meantime, the long list seems too complicated, and several of the social options are ones only I would use, if at all. I've pre-populated my News/Event release templates to include all my usual properties.

On regular two-column templates, I'd recommend:

Remove:

    <parameter name="social-tagboard" type="text" group="Everyone" prompt="Tagboard URL" alt="Add a Tagboard URL to include a link in the sidebar."></parameter>
    <parameter name="social-storify" type="text" group="Everyone" prompt="Storify URL" alt="Add a Storify URL to include a link in the sidebar."></parameter>
    <parameter name="social-linkedin" type="text" group="Everyone" prompt="LinkedIn URL" alt="Add a LinkedIn URL to include a link in the sidebar."></parameter>
    <parameter name="social-pinterest" type="text" group="Everyone" prompt="Pinterest URL" alt="Add a Pinterest URL to include a link in the sidebar."></parameter>
    <parameter name="social-flickr" type="text" group="Everyone" prompt="Flickr URL" alt="Add a Flickr URL to include a link in the sidebar."></parameter>
    <parameter name="social-rss" type="text" group="Everyone" prompt="RSS URL" alt="Add an RSS URL to include a link in the sidebar."></parameter>
    <parameter name="social-rebelmouse" type="text" group="Everyone" prompt="Rebelmouse URL" alt="Add a Rebelmouse URL to include a link in the sidebar."></parameter>

Keep:

	<parameter name="social-facebook" type="text" group="Everyone" prompt="Facebook URL" alt="Add a Facebook URL to include a link in the sidebar."></parameter>
    <parameter name="social-twitter" type="text" group="Everyone" prompt="Twitter URL" alt="Add a Twitter URL to include a link in the sidebar."></parameter>
    <parameter name="social-instagram" type="text" group="Everyone" prompt="Instagram URL" alt="Add an Instagram URL to include a link in the sidebar."></parameter>
    <parameter name="social-youtube" type="text" group="Everyone" prompt="YouTube URL" alt="Add a YouTube URL to include a link in the sidebar."></parameter>

**Comment by michaelcgorman** [comment]
Done.
