### ISSUE TITLE
Test: Department Header Image Size

### ISSUE THREAD

**Issue by robertfrankiii** [iwu/iwu-website#65]
The visible header image height should be decreased to 140px. Currently, I think the height on the test site decreases to 150px at the 480px width breakpoint. The new height can be for all sizes.

![small-header-image-01](https://cloud.githubusercontent.com/assets/14199085/13853623/8a65c2c6-ec35-11e5-937d-1ab407d02d76.png)

I'll deal with changing the images once this is coded. How will this affect the required sizes for the images?

**Comment by michaelcgorman** [comment]
The new height is in effect on test.

**Comment by michaelcgorman** [comment]
If we want to keep the same width breakpoints, here are the sizes we'll need (assuming I've done the math right, which I'm not certain of this time):
- 4000x500 (alternates/[name]-2x.jpg)
- 2400x368 (alternates/[name]-1200-2x.jpg)
- 2000x250 ([name].jpg)
- 1960x384 (alternates/[name]-980-2x.jpg)
- 1536x660 (alternates/[name]-768-2x.jpg)
- 1200x184 (alternates/[name]-1200.jpg)
- 980x192 (alternates/[name]-980.jpg)
- 768x330 (alternates/[name]-768.jpg)

Give this a shot on one image and let's see how it goes.

**Comment by robertfrankiii** [comment]
I've tried it on the /art/ site and it seems to be working fine. Thanks!
