### ISSUE TITLE
Test: Local Navigation

### ISSUE THREAD

**Issue by robertfrankiii** [iwu/iwu-website#66]
The local navigation has changed color to the Wesleyan green and a tan bar has been added to the bottom (#f2eee7). The active page color is now #9dcb90 and the triangles are now #196047.

![nav-1](https://cloud.githubusercontent.com/assets/14199085/13854085/ced9b078-ec37-11e5-96a5-a50639024a7d.png)

Would it be possible to have a hover effect that does not trigger a dropdown? the background color would change to #64956a. Also, could the dropdown triangles still display (like in the image below), or would they have to disappear?

![nav-hover-01](https://cloud.githubusercontent.com/assets/14199085/13854232/7637d020-ec38-11e5-9e18-64ee3eb5207d.png)

Dropdowns: The triangle color and background of the dropdown is #124332. Let's use this for the main navigation as well for mobile.

![dropdown-01](https://cloud.githubusercontent.com/assets/14199085/13854387/4054ca84-ec39-11e5-8960-3ee677cd947d.png)

Mobile Menu text and hamburger symbol will be white.

AI file:
https://drive.google.com/file/d/0B3D4GYlD-TUmeFJ3VEx1ZkFMbDQ/view?usp=sharing

**Comment by michaelcgorman** [comment]
I *think* most of this is good to test now.

**Comment by robertfrankiii** [comment]
Looks good to me except the mobile version is still the gradient background - let me know if you need any files from me for those breakpoints. Thanks!

**Comment by michaelcgorman** [comment]
Fixed.
