### ISSUE TITLE
Test: Secondary Content Area (side column)

### ISSUE THREAD

**Issue by robertfrankiii** [iwu/iwu-website#67]
We'd like to add three buttons at the top of the side column content and add a title to the contact section:
![side-column-01](https://cloud.githubusercontent.com/assets/14199085/13855075/aa55fdce-ec3c-11e5-94de-93b4fb48efc0.png)
You can refer to the AI linked to in the navigation Issue.
Colors are #006647, #64956a, and #8ab27f

Apply Now would link to the [How to Apply page](https://www.iwu.edu/admissions/applications/).
Campus Visit would link to the [Arrange a Visit page](https://www.iwu.edu/admissions/visit/).
The request Info button would link to the [Request Info page](https://admissions.iwu.edu/register/informationrequest) (which will hopefully be streamlined soon...)

These should only display on Academic departments. Would the best way to do that is to just add them to the page properties options?

The title for the contact area should probably be editable - for departments that aren't academic.

**Comment by michaelcgorman** [comment]
Check out /1world/html-elements.html on test.

**Comment by michaelcgorman** [comment]
How's it looking, @robertfrankiii?

BTW, since this would apply department-wide, I decided to try out directory variables instead of page parameters. That means no global find-and-replaces, which is nice.

**Comment by ckelch** [comment]
By the way, Jan Alvis is done with the streamlined [Request Information form](https://admissions.iwu.edu/register/informationrequest).

**Comment by robertfrankiii** [comment]
Sorry this took me so long to get back to. Can we decrease the margins on the top and bottom of the buttons to 10 pixels? I think the Apply Now button needs a different hover background color since it doesn't change at the moment. Can we make the background change to the dark green that is the normal background color of the Request Information button?

**Comment by michaelcgorman** [comment]
Done.

**Comment by robertfrankiii** [comment]
Can we change the wording of the third button to "Visit Campus"? Also, what's the plan for these? How will we get these onto the academic department pages? Page Properties? @aaubryiwu  Will these only go on their index pages, or all of their pages?

**Comment by aaubryiwu** [comment]
We'd want them on all academic department pages, with possible exceptions for /faculty/ pages.

**Comment by aaubryiwu** [comment]
Robert's note in his initial request -- "The title for the contact area should probably be editable - for departments that aren't academic" -- was the first piece of feedback we got on the new design (from SON). 
Is this somehow possible? Admissions wants the buttons, but doesn't want to call Bob Murray their Department Chair.

**Comment by michaelcgorman** [comment]
Do we even need to say anything there? Could I just remove the "Department Chair" text entirely? That would be easier than trying to create an editable field at this point.

If we go that route, we can also add it to the list of fields we'd like as directory variables for the time when we switch from controlling this stuff through the page properties to controlling it all through directory variables.

**Comment by aaubryiwu** [comment]
Can we keep it as a directory variable, but untie it from the buttons? Then we could have it on academic departments but not on Admissions, where we want the buttons but the title isn't relevant and they see having neither as the least offensive option.

is_academic  (for the buttons)
is_department ...? (for "Department Chair")

Or is that just as tricky?

**Comment by aaubryiwu** [comment]
Can we keep it as a directory variable like the banners, but untie it from the buttons? Then we could have it on academic departments but not on Admissions, where we want the buttons but the title isn't relevant and they see having neither as the least offensive option.

is_academic (for the buttons)
is_department ...? (for "Department Chair")

Or is that just as tricky?

**Comment by michaelcgorman** [comment]
Yes, ideally I wouldn't have to add a directory variable right now.

**Comment by aaubryiwu** [comment]
We talked this over with Admissions -- and we've heard from an additional director who doesn't want to be called chair. Could we remove the "Department Chair" text altogether and just leave the buttons, followed by the default contact info?

**Comment by michaelcgorman** [comment]
Done.
