### ISSUE TITLE
Test - Homepage Carousel Arrows

### ISSUE THREAD

**Issue by robertfrankiii** [iwu/iwu-website#69]
Below is the mockup for the arrows that will replace the black fades.

They are 40px tall and 30px wide and I have them at 75% opacity. When hovered over, opacity goes to 100%.

![homepage-arrows-01](https://cloud.githubusercontent.com/assets/14199085/14865933/bed8e44a-0c86-11e6-8445-6b2d95211ac3.png)

Here is a flat version with the dropshadow included.
![arrow](https://cloud.githubusercontent.com/assets/14199085/14866469/8d46278c-0c89-11e6-8f55-d3170226088c.png)

Let me know if you need anything.

**Comment by michaelcgorman** [comment]
Done.
