### ISSUE TITLE
Test - Homepage: Carousel Indicator Bar

### ISSUE THREAD

**Issue by robertfrankiii** [iwu/iwu-website#73]
Please add the carousel indicator bar that displayed below the homepage carousel back onto the page.

**Comment by michaelcgorman** [comment]
Turns out I did not just comment it out, so it'll need to be rewritten unless you happen to have saved a copy?

**Comment by robertfrankiii** [comment]
As a matter of fact, I do! But I have no idea why...

**Comment by michaelcgorman** [comment]
Hurrah! Done.

**Comment by robertfrankiii** [comment]
I just noticed a bug on my phone with the bar. When I scroll down on my phone, then back up - the background pattern and image thumbnails disappear. The green active circle still displays though.

![img_0677](https://cloud.githubusercontent.com/assets/14199085/15261429/18487386-1922-11e6-80fd-51eba0c521e4.PNG)

**Comment by michaelcgorman** [comment]
Unable to replicate. Refresh your cache?

**Comment by robertfrankiii** [comment]
Just did and I'm still seeing this happen (so is Ann). Would you like to inspect my phone?
