### ISSUE TITLE
Test - Homepage: Black Gradient on Carousel

### ISSUE THREAD

**Issue by robertfrankiii** [iwu/iwu-website#74]
Could we add a black gradient (attached) to the bottom of the carousel on the homepage that goes full width behind the text? I think this will improve the readability.

![gradient-01](https://cloud.githubusercontent.com/assets/14199085/15260159/d847de9a-191a-11e6-9ab9-4ba6d4c1e3cd.png)

**Comment by michaelcgorman** [comment]
No problem. Could you describe the gradient, though? I'd rather do it with CSS than an image. Is it pure black? How tall? 0% opacity at the top to 100% at the bottom?

**Comment by robertfrankiii** [comment]
150px tall. Pure black. 0% at the top to 35% at the bottom.

**Comment by michaelcgorman** [comment]
How's that?

**Comment by robertfrankiii** [comment]
This looks great on larger sized screens, but I'm concerned about the readability on phones still. Can we bump up the opacity at the bottom to 50% at the 480 breakpoint and smaller?

**Comment by michaelcgorman** [comment]
BTW, do we want to just hide the arrows at a certain size? The thumbnails seem like a better toggle on mobile, anyway, so we wouldn't lose any functionality.

**Comment by robertfrankiii** [comment]
Yes!! I was just searching for the arrow issue to suggest that. I'm not entirely sure about the size where we want to lose them. How does everything below 480px sound?

**Comment by michaelcgorman** [comment]
Done.

**Comment by robertfrankiii** [comment]
That looks great! Quick question though: can we also increase the height of the gradient by 50px at the same time?

**Comment by michaelcgorman** [comment]
Oh, is that what you meant earlier? I thought you meant bumping the opacity up to 50%. Fixed.

**Comment by robertfrankiii** [comment]
Sorry for the confusion - Can we do both at that breakpoint? Increase the opacity to 50% _and_ increase the height by 50px?

**Comment by michaelcgorman** [comment]
Done.
