### ISSUE TITLE
Test - About level 2 page: Map Section

### ISSUE THREAD

**Issue by robertfrankiii** [iwu/iwu-website#77]
Do you still need to code a map section for the level two pages, or is that something I can do?

![about-map](https://cloud.githubusercontent.com/assets/14199085/15328805/d6535a8e-1c1b-11e6-860f-982bac42064c.png)

**Comment by michaelcgorman** [comment]
You should be able to do that... I don't see anything complicated. Looks like just two col-md-6 divs, maybe?

**Comment by robertfrankiii** [comment]
That worked, thanks. (I forgot this issue existed when I submitted the other one about embedding google maps).
