### ISSUE TITLE
Test - Level 2 section: border-bottom div

### ISSUE THREAD

**Issue by robertfrankiii** [iwu/iwu-website#78]
The border-bottom div should have a border at the bottom and a background pattern exactly like the callout box snippet.

![about-border-section](https://cloud.githubusercontent.com/assets/14199085/15328858/13d56c58-1c1c-11e6-8183-57c2db0f97e6.png)

**Comment by robertfrankiii** [comment]
Is this change live? I can't see the pattern background.

**Comment by michaelcgorman** [comment]
Hmm... It's there on /aboutiwu/, which is where I was testing. Not sure why it's not showing up elsewhere.

**Comment by robertfrankiii** [comment]
I'm not seeing it on the about page:

![screen shot 2016-05-23 at 8 39 17 am](https://cloud.githubusercontent.com/assets/14199085/15472650/e1779d62-20c1-11e6-91e0-7812f323e0ad.png)

**Comment by michaelcgorman** [comment]
Ah, right. The background. Done.
