### ISSUE TITLE
Test-Level 2 Page Section: Video Gallery

### ISSUE THREAD

**Issue by robertfrankiii** [iwu/iwu-website#80]
Have you created this section yet?

<img width="1964" alt="video-gallery-section" src="https://cloud.githubusercontent.com/assets/14199085/15474046/9da7f472-20c8-11e6-9303-bc98b5a0ad4c.png">

I'll need it for the Fine Arts and Student Life pages.

**Comment by michaelcgorman** [comment]
I've made some progress on this:
![screen shot 2016-05-26 at 11 04 38](https://cloud.githubusercontent.com/assets/313667/15581388/b65a074c-2331-11e6-93f4-02e9e66e0b7a.png)

Now that we're dropping the Fine Arts page, is it absolutely necessary for the Student Life page or is there another, already existing, layout for this info? It's not exactly going to be quick for me to finish laying this out.

**Comment by michaelcgorman** [comment]
Any decision on this?

**Comment by robertfrankiii** [comment]
Let's forget this for this launch.
