### ISSUE TITLE
Banner Images using Directory Variables

### ISSUE THREAD

**Issue by ckelch** [iwu/iwu-website#83]
Thinking about the website redesign launch, it might be nice to have all of this set at the director variable level, since most people never change these and we don't have any departments who have a different images for parts of their website. We will make sure that all image names are different then current default banner names currently.

**Comment by michaelcgorman** [comment]
Done.

The new place to edit header background images is the directory variable form. When you're looking at a directory in a file listing, hover over "edit" and choose "access". Scroll to the bottom of the modal dialog. If there isn't one there already, hit the "add" button and choose "header_background". The default is "header-art.jpg", but for any directory that has another file selected on this form, that'll be overridden.

Important to note: changes to this setting will not take effect immediately; you'll have to republish the entire directory. Also, the old templates will still pull from the page properties, so republishing with this new variable in place won't change the site at all until the new templates go into effect next month.

Finally, if you don't republish a given file before the redesign goes into effect, it'll pull the header background from the old design.
