### ISSUE TITLE
Test - Level 2 pages: flex-image-grid section

### ISSUE THREAD

**Issue by robertfrankiii** [iwu/iwu-website#89]
Would it be possible to have this section breakdown similar to the mockups at smaller screen sizes? Also, could they stay squares?

980px:
<img width="1020" alt="screen shot 2016-05-28 at 12 58 21 pm" src="https://cloud.githubusercontent.com/assets/14199085/15628923/e43bcae4-24d3-11e6-8b66-4a61316fcc1b.png">

768px:
<img width="1020" alt="screen shot 2016-05-28 at 12 58 21 pm" src="https://cloud.githubusercontent.com/assets/14199085/15628926/f270a3aa-24d3-11e6-9bfb-80108b9480a6.png">

480px:
<img width="553" alt="screen shot 2016-05-28 at 12 59 24 pm" src="https://cloud.githubusercontent.com/assets/14199085/15628927/06638f62-24d4-11e6-9a45-cd52fef4d1f7.png">

320px:
<img width="396" alt="screen shot 2016-05-28 at 12 59 44 pm" src="https://cloud.githubusercontent.com/assets/14199085/15628963/114ea81c-24d4-11e6-991e-738bdf38208b.png">

**Comment by michaelcgorman** [comment]
Alright, I think it's better now. Not _quite_ what you'd designed, but closer.

**Comment by aaubryiwu** [comment]
I'm still having some weirdness on mobile sizes. (no longer zoomed)

![img_1030](https://cloud.githubusercontent.com/assets/14187046/15864493/fa6fd032-2c9c-11e6-8f6e-4b8368e97871.PNG)

![img_1031](https://cloud.githubusercontent.com/assets/14187046/15864496/fdbbbb2a-2c9c-11e6-8325-72b87450694d.PNG)

**Comment by michaelcgorman** [comment]
That's an issue with the carousel above it, not the flex-image-grid. Commenting the carousel fixed it.

**Comment by michaelcgorman** [comment]
Fixed the carousel. The lead-in text was inside the carousel, but the left/right buttons are set to 100% height and didn't start until below the lead-in text. Moved the lead-in text outside of the carousel and it appears to be fixed.
