### ISSUE TITLE
Test - All Level 2 Pages: Navigation Dissapearing

### ISSUE THREAD

**Issue by robertfrankiii** [iwu/iwu-website#90]
One my phone, when I scroll down the navigation and top section after the navigation disappear. They reappear when I scroll back up.

**Comment by michaelcgorman** [comment]
I am not able to replicate this issue.

**Comment by michaelcgorman** [comment]
The template file was outputting div#header-container even though that element is not used on second-level pages. It was transparently covering up the local nav.
