### ISSUE TITLE
Horizontal scroll on second-level pages

### ISSUE THREAD

**Issue by michaelcgorman** [iwu/iwu-website#94]
Some second-level pages scroll horizontally. The only thing visible to the right of the main column is the search button. Affected pages are:

- /aboutiwu/
- /student-life/

Figure out what's going on with that. Super weird.

**Comment by michaelcgorman** [comment]
@aaubryiwu is seeing this on more pages than I did:

> On both Chrome & Safari mobile, all except /giving/ and /after-wesleyan/ landing pages allow scrolling off into white space on the right.

**Comment by michaelcgorman** [comment]
I'm not seeing it on /aboutiwu/, /giving/, or /after-wesleyan/. I am seeing it on /academics/, /admissions/, and /student-life/.

**Comment by aaubryiwu** [comment]
I had to scroll down a ways on /aboutiwu/ before having the issue.

**Comment by michaelcgorman** [comment]
/aboutiwu/ is scrolling because of a rogue regional map at the bottom of the page that is 500px wide even when the screen isn't. I've set `max-width: 100%` on all `.col-md-6 img` elements to fix it; hopefully that won't have too many unintended side effects.

**Comment by michaelcgorman** [comment]
The only remaining second-level page that scrolls horizontally for me is /admissions/.

**Comment by michaelcgorman** [comment]
/admissions/ is fixed. I don't know of any other second-level pages that scroll horizontally.
