### ISSUE TITLE
No local navigation in Safari - iPhone 6s

### ISSUE THREAD

**Issue by aaubryiwu** [iwu/iwu-website#97]
![img_1025](https://cloud.githubusercontent.com/assets/14187046/15856723/fcb078f8-2c7c-11e6-907c-23b7b412f421.PNG)

**Comment by michaelcgorman** [comment]
Are you sure? It's there for me. Same page, same browser. iPhone 6 Plus.

**Comment by aaubryiwu** [comment]
Yep. But I do get local nav on departmental pages. (just have to manually enter url to get there)

**Comment by michaelcgorman** [comment]
This is still befuddling. Have you cleared the cache through Settings (i.e., not just refresh the page)?

**Comment by aaubryiwu** [comment]
Yes. Cleared for all time.

**Comment by michaelcgorman** [comment]
Safari doesn't give a time period, as far as I can tell. There are two places in iOS Settings to clear:
![img_4062](https://cloud.githubusercontent.com/assets/313667/15860510/07f96fd2-2c8f-11e6-82ff-43ae73549a30.jpg)
and
![img_4063](https://cloud.githubusercontent.com/assets/313667/15860514/0b5a290a-2c8f-11e6-9080-382abc8b3127.jpg)

**Comment by aaubryiwu** [comment]
Yes -- I've tried clearing w/in app and w/in settings.

**Comment by michaelcgorman** [comment]
This really makes absolutely zero sense.

**Comment by robertfrankiii** [comment]
I've cleared everything from safari on my phone (5s) and I am seeing the same thing Ann is seeing on all of the level 2 pages and the homepage (the carousel indicator bar).

**Comment by michaelcgorman** [comment]
In this issue we're only talking about the local navigation. If you're having issues with a carousel indicator bar, that should go in a different issue.

**Comment by michaelcgorman** [comment]
What about in Private Browsing Mode?

**Comment by michaelcgorman** [comment]
Alright, the issue appears to be tied to header photos that are taller than expected, likely due to longer text strings inside the carousel. I'm going to try manually bumping up the default heights.

**Comment by michaelcgorman** [comment]
Current sizes, in case we need them in the future:
`@media (max-height: 500px) and (max-width: 479px) {
	#header-carousel .carousel-inner > .item {
		height: 400px;
	}
}
@media (min-height: 901px) and (min-width: 480px) {
	.homepage #header-wrap,
	.second-level #header-wrap,
	#header-carousel .carousel-inner > .item {
		height: 750px;
	}
}
@media (min-height: 801px) and (max-height: 900px) and (min-width: 480px) {
	.homepage #header-wrap,
	.second-level #header-wrap,
	#header-carousel .carousel-inner > .item {
		height: 650px;
	}
}
@media (min-height: 701px) and (max-height: 800px) and (min-width: 480px) {
	.homepage #header-wrap,
	.second-level #header-wrap,
	#header-carousel .carousel-inner > .item {
		height: 550px;
	}
}
@media (min-height: 501px) and (min-width: 480px) and (max-width: 767px) {
	.homepage #header-wrap,
	.second-level #header-wrap,
	#header-carousel .carousel-inner > .item {
		height: 520px;
	}
}
@media (min-height: 601px) and (max-height: 700px) and (min-width: 480px) {
	.homepage #header-wrap,
	.second-level #header-wrap,
	#header-carousel .carousel-inner > .item {
		height: 450px;
	}
}
@media (min-height: 401px) and (max-height: 500px) and (min-width: 480px) and (max-width: 767px) {
	.homepage #header-wrap,
	.second-level #header-wrap,
	#header-carousel .carousel-inner > .item {
		height: 430px;
	}
}
@media (min-height: 501px) and (max-width: 479px) {
	.homepage #header-wrap,
	.second-level #header-wrap,
	#header-carousel .carousel-inner > .item {
		height: 400px;
	}
}
@media (min-height: 501px) and (max-height: 600px) and (min-width: 768px) {
	.homepage #header-wrap,
	.second-level #header-wrap,
	#header-carousel .carousel-inner > .item {
		height: 350px;
	}
}
@media (max-height: 400px) and (min-width: 480px) and (max-width: 767px) {
	.homepage #header-wrap,
	.second-level #header-wrap,
	#header-carousel .carousel-inner > .item {
		height: 350px;
	}
}
@media (max-height: 500px) and (min-width: 768px) {
	.homepage #header-wrap,
	.second-level #header-wrap,
	#header-carousel .carousel-inner > .item {
		height: 330px;
	}
}`

**Comment by michaelcgorman** [comment]
Alright, I'm calling this fixed. That ended up not being the solution; I ended up reverting all of those sizes to the originals and instead setting the carousel-inner and the carousel-inner items to height: 100% instead of defining it as the same size as the wrap.

**Comment by robertfrankiii** [comment]
I now see this when I initially load all of the level 2 pages and homepage. The text is cut off in the carousel.
![img_0686](https://cloud.githubusercontent.com/assets/14199085/15863852/3fbef9a4-2c9a-11e6-9dee-08017860b3e4.jpg)

But it seems to be corrected when I turn my phone horizontal:
![img_0687](https://cloud.githubusercontent.com/assets/14199085/15863871/4df9ad70-2c9a-11e6-98a9-13286a950f0d.jpg)

**Comment by michaelcgorman** [comment]
Oh, so you want to be able to read the text? Very demanding.

**Comment by michaelcgorman** [comment]
How's it look now (in test)?

**Comment by robertfrankiii** [comment]
It looks the same.

**Comment by michaelcgorman** [comment]
This is fixed now, right @aaubryiwu and @robertfrankiii?
