### ISSUE TITLE
Mobile Chrome oddities - iPhone 6s

### ISSUE THREAD

**Issue by aaubryiwu** [iwu/iwu-website#98]
Local navigation shows up, but only after scrolling down a bit; the first view is as below.

![img_1022](https://cloud.githubusercontent.com/assets/14187046/15856762/47015b2a-2c7d-11e6-92a1-932c4dc9aaa9.PNG)

![img_1023](https://cloud.githubusercontent.com/assets/14187046/15856764/4d93b1b8-2c7d-11e6-9baa-d210f09832a1.PNG)

**Comment by michaelcgorman** [comment]
Please confirm cache state. These are not problems I'm seeing.

**Comment by aaubryiwu** [comment]
I cleared cache on all browsers & devices, forced quit/restarted.

**Comment by michaelcgorman** [comment]
Version number? I believe I'm up-to-date at 51.0.2704.64.

**Comment by aaubryiwu** [comment]
I have the same version.

**Comment by aaubryiwu** [comment]
Home page
![img_1026](https://cloud.githubusercontent.com/assets/14187046/15858291/69937eea-2c85-11e6-8365-09a03ec0ace2.PNG)

Videos on all level 2s
![img_1027](https://cloud.githubusercontent.com/assets/14187046/15858260/3bad7d78-2c85-11e6-93c5-c02e44e35388.PNG)

Anywhere these occur:
![img_1028](https://cloud.githubusercontent.com/assets/14187046/15858256/39701dea-2c85-11e6-9bd9-cc0d8329f480.PNG)
![img_1029](https://cloud.githubusercontent.com/assets/14187046/15858264/3f30e2b4-2c85-11e6-82c4-527bea5240f4.PNG)

**Comment by michaelcgorman** [comment]
The initial two screenshots should be fixed now. Please file separate issues for separate bugs.
