### ISSUE TITLE
Phantom big stat display - After Wesleyan on Firefox

### ISSUE THREAD

**Issue by aaubryiwu** [iwu/iwu-website#99]
Firefox 46.0.1 on Mac Yosemite. Page seems OK on desktop Safari & Chrome.

![firefox mac](https://cloud.githubusercontent.com/assets/14187046/15856892/01efc5b6-2c7e-11e6-9018-be44d3932c30.png)

**Comment by aaubryiwu** [comment]
Oops - now I'm seeing the same phantom on Chrome.

**Comment by michaelcgorman** [comment]
Fixed.
